

# Add 'team: backend' if in the PR are changes in files located in app/src folder 
team:backend: app/src/**/*

team:qa: app/tests/**/*

team:docs: app/README.md

team:devops:  
- app/Dockerfile 
- app/Taskfile.yml