
# Add 'repo' label to any root file changes
repo:
- '*'

# Add 'team: backend' if in the PR are changes in files located in app/src folder 
backend: 
- 'src/**/*'
qa: 
- 'tests/**/*'
'team: docs': 
- 'README.md'
devops:  
- 'Dockerfile' 
- 'Taskfile.yml'
