

# Adding 'team: backend' if in the PR there are changes in files located in app/src folder 
'team: backend': 
- 'src/**/*'

# Adding 'team: qa' if in the PR there are changes in files located in app/tests folder 
'team: qa': 
- 'tests/**/*'

# Adding 'team: qa' if in the PR there are changes to the README.md file
'team: docs': 
- 'README.md'

# Adding 'team: devops' if in the PR there are changes to the devops file
'team: devops':  
- 'Dockerfile' 
- 'Taskfile.yml'
