# https://taskfile.dev

version: '3'

vars:
  DOCKER_IMAGE_NAME: $(echo "$DOCKER_IMAGE_NAME")
  NEW_DOCKER_IMAGE_NAME: $(echo "$NEW_DOCKER_IMAGE_NAME")
  PUSH_DOCKER_IMAGE_NAME: $(echo "$PUSH_DOCKER_IMAGE_NAME")
tasks:
  docker:build:
    cmds:
      - docker build -t {{ .DOCKER_IMAGE_NAME }} .

  docker:tag:
    cmds:
      - docker tag {{ .DOCKER_IMAGE_NAME }} {{ .NEW_DOCKER_IMAGE_NAME }}
  
  docker:push:
    cmds:
      - docker push {{ .PUSH_DOCKER_IMAGE_NAME }}

  docker:run:
    cmds:
      - docker run -p 8080:8080 {{ .DOCKER_IMAGE_NAME }}:latest
